# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  name: Default
  

steps:
- task: CopyFiles@2
  inputs:
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)Templates'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: Npm@1
  inputs:
    command: 'install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/js-e2e-express-mongodb$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'webapp'
    targetPath: '$(System.DefaultWorkingDirectory)'
    

